apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-static-website-ingress
  namespace: demo-1
spec:
  ingressClassName: nginx
  rules:
  - host: 'static.rajeevupreti.com.np'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-static-website-service
            port:
              number: 80

  - host: 'emqx.rajeevupreti.com.np'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emqx-service
            port:
              number: 18083