filebeat.inputs:
- type: docker
  containers.ids:
  - "*"
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
      matchers:
      - fields.container.name: "name=(.+),"
  fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
